import { Plus } from 'lucide-react'
import {
  BrandGithub,
  BrandV2ex,
  BrandJuejin,
  BrandBilibili,
  BrandYoutubeFilled,
  BrandDouban,
  BrandReddit,
  BrandTaobao,
  BrandAppleFilled,
  BrandWeibo,
  BrandMedium,
} from '@/svg/icon-collection'
import type { SiteItem, WidgetItem } from './types'
import type { ComponentType, SVGProps } from 'react'

// 图标映射表
export const iconMap: Record<string, ComponentType<SVGProps<SVGSVGElement>>> = {
  github: BrandGithub,
  juejin: BrandJuejin,
  v2ex: BrandV2ex,
  bilibili: BrandBilibili,
  youtube: BrandYoutubeFilled,
  douban: BrandDouban,
  taobao: BrandTaobao,
  apple: BrandAppleFilled,
  weibo: BrandWeibo,
  medium: BrandMedium,
}

// 预设网站
export const presetSites: SiteItem[] = [
  {
    id: 'github',
    size: '1x1',
    title: 'GitHub',
    url: 'https://github.com',
    favicon: '',
    icon: BrandGithub,
    type: 'site',
  },
  {
    id: 'juejin',
    size: '1x1',
    title: '稀土掘金',
    url: 'https://juejin.cn',
    favicon: '',
    icon: BrandJuejin,
    type: 'site',
  },
  {
    id: 'v2ex',
    size: '1x1',
    title: 'V2EX',
    url: 'https://www.v2ex.com',
    favicon: '',
    icon: BrandV2ex,
    type: 'site',
  },
  {
    id: 'bilibili',
    size: '1x1',
    title: 'Bilibili',
    url: 'https://www.bilibili.com',
    favicon: '',
    icon: BrandBilibili,
    type: 'site',
  },
  {
    id: 'youtube',
    size: '1x1',
    title: 'YouTube',
    url: 'https://www.youtube.com',
    favicon: '',
    icon: BrandYoutubeFilled,
    type: 'site',
  },
  {
    id: 'douban',
    size: '1x1',
    title: '豆瓣',
    url: 'https://www.douban.com',
    favicon: '',
    icon: BrandDouban,
    type: 'site',
  },
  {
    id: 'reddit',
    size: '1x1',
    title: 'Reddit',
    url: 'https://www.reddit.com',
    favicon: '',
    icon: BrandReddit,
    type: 'site',
  },
  {
    id: 'taobao',
    size: '1x1',
    title: '淘宝',
    url: 'https://www.taobao.com',
    favicon: '',
    icon: BrandTaobao,
    type: 'site',
  },
  {
    id: 'apple',
    size: '1x1',
    title: 'Apple',
    url: 'https://www.apple.com',
    favicon: '',
    icon: BrandAppleFilled,
    type: 'site',
  },
  {
    id: 'weibo',
    size: '1x1',
    title: '微博',
    url: 'https://www.weibo.com',
    favicon: '',
    icon: BrandWeibo,
    type: 'site',
  },
  {
    id: 'medium',
    size: '1x1',
    title: 'Medium',
    url: 'https://www.medium.com',
    favicon: '',
    icon: BrandMedium,
    type: 'site',
  },
  // ========== Mock 数据：模拟满屏效果 ==========
  {
    id: 'mock-google',
    size: '1x1',
    title: 'Google',
    url: 'https://www.google.com',
    favicon: 'https://www.google.com/favicon.ico',
    type: 'site',
  },
  {
    id: 'mock-twitter',
    size: '1x1',
    title: 'Twitter',
    url: 'https://twitter.com',
    favicon: 'https://twitter.com/favicon.ico',
    type: 'site',
  },
  {
    id: 'mock-facebook',
    size: '1x1',
    title: 'Facebook',
    url: 'https://www.facebook.com',
    favicon: 'https://www.facebook.com/favicon.ico',
    type: 'site',
  },
  {
    id: 'mock-instagram',
    size: '1x1',
    title: 'Instagram',
    url: 'https://www.instagram.com',
    favicon: 'https://www.instagram.com/favicon.ico',
    type: 'site',
  },
  {
    id: 'mock-linkedin',
    size: '1x1',
    title: 'LinkedIn',
    url: 'https://www.linkedin.com',
    favicon: 'https://www.linkedin.com/favicon.ico',
    type: 'site',
  },
  {
    id: 'mock-netflix',
    size: '1x1',
    title: 'Netflix',
    url: 'https://www.netflix.com',
    favicon: 'https://www.netflix.com/favicon.ico',
    type: 'site',
  },
  {
    id: 'mock-spotify',
    size: '1x1',
    title: 'Spotify',
    url: 'https://www.spotify.com',
    favicon: 'https://www.spotify.com/favicon.ico',
    type: 'site',
  },
  {
    id: 'mock-amazon',
    size: '1x1',
    title: 'Amazon',
    url: 'https://www.amazon.com',
    favicon: 'https://www.amazon.com/favicon.ico',
    type: 'site',
  },
  {
    id: 'mock-notion',
    size: '1x1',
    title: 'Notion',
    url: 'https://www.notion.so',
    favicon: 'https://www.notion.so/favicon.ico',
    type: 'site',
  },
  {
    id: 'mock-figma',
    size: '1x1',
    title: 'Figma',
    url: 'https://www.figma.com',
    favicon: 'https://www.figma.com/favicon.ico',
    type: 'site',
  },
  {
    id: 'mock-slack',
    size: '1x1',
    title: 'Slack',
    url: 'https://slack.com',
    favicon: 'https://slack.com/favicon.ico',
    type: 'site',
  },
  {
    id: 'mock-discord',
    size: '1x1',
    title: 'Discord',
    url: 'https://discord.com',
    favicon: 'https://discord.com/favicon.ico',
    type: 'site',
  },
  {
    id: 'mock-twitch',
    size: '1x1',
    title: 'Twitch',
    url: 'https://www.twitch.tv',
    favicon: 'https://www.twitch.tv/favicon.ico',
    type: 'site',
  },
  {
    id: 'mock-zhihu',
    size: '1x1',
    title: '知乎',
    url: 'https://www.zhihu.com',
    favicon: 'https://www.zhihu.com/favicon.ico',
    type: 'site',
  },
  {
    id: 'mock-jd',
    size: '1x1',
    title: '京东',
    url: 'https://www.jd.com',
    favicon: 'https://www.jd.com/favicon.ico',
    type: 'site',
  },
  {
    id: 'mock-tmall',
    size: '1x1',
    title: '天猫',
    url: 'https://www.tmall.com',
    favicon: 'https://www.tmall.com/favicon.ico',
    type: 'site',
  },
  {
    id: 'mock-baidu',
    size: '1x1',
    title: '百度',
    url: 'https://www.baidu.com',
    favicon: 'https://www.baidu.com/favicon.ico',
    type: 'site',
  },
  {
    id: 'mock-bing',
    size: '1x1',
    title: 'Bing',
    url: 'https://www.bing.com',
    favicon: 'https://www.bing.com/favicon.ico',
    type: 'site',
  },
  {
    id: 'mock-stackoverflow',
    size: '1x1',
    title: 'Stack Overflow',
    url: 'https://stackoverflow.com',
    favicon: 'https://stackoverflow.com/favicon.ico',
    type: 'site',
  },
  {
    id: 'mock-npm',
    size: '1x1',
    title: 'NPM',
    url: 'https://www.npmjs.com',
    favicon: 'https://www.npmjs.com/favicon.ico',
    type: 'site',
  },
  {
    id: 'mock-vercel',
    size: '1x1',
    title: 'Vercel',
    url: 'https://vercel.com',
    favicon: 'https://vercel.com/favicon.ico',
    type: 'site',
  },
  {
    id: 'mock-netlify',
    size: '1x1',
    title: 'Netlify',
    url: 'https://www.netlify.com',
    favicon: 'https://www.netlify.com/favicon.ico',
    type: 'site',
  },
  {
    id: 'mock-codepen',
    size: '1x1',
    title: 'CodePen',
    url: 'https://codepen.io',
    favicon: 'https://codepen.io/favicon.ico',
    type: 'site',
  },
  {
    id: 'mock-dribbble',
    size: '1x1',
    title: 'Dribbble',
    url: 'https://dribbble.com',
    favicon: 'https://dribbble.com/favicon.ico',
    type: 'site',
  },
  {
    id: 'mock-behance',
    size: '1x1',
    title: 'Behance',
    url: 'https://www.behance.net',
    favicon: 'https://www.behance.net/favicon.ico',
    type: 'site',
  },
  {
    id: 'mock-pinterest',
    size: '1x1',
    title: 'Pinterest',
    url: 'https://www.pinterest.com',
    favicon: 'https://www.pinterest.com/favicon.ico',
    type: 'site',
  },
  {
    id: 'mock-tiktok',
    size: '1x1',
    title: 'TikTok',
    url: 'https://www.tiktok.com',
    favicon: 'https://www.tiktok.com/favicon.ico',
    type: 'site',
  },
  {
    id: 'mock-wechat',
    size: '1x1',
    title: '微信',
    url: 'https://weixin.qq.com',
    favicon: 'https://weixin.qq.com/favicon.ico',
    type: 'site',
  },
  {
    id: 'mock-qq',
    size: '1x1',
    title: 'QQ',
    url: 'https://www.qq.com',
    favicon: 'https://www.qq.com/favicon.ico',
    type: 'site',
  },
  {
    id: 'mock-163',
    size: '1x1',
    title: '网易',
    url: 'https://www.163.com',
    favicon: 'https://www.163.com/favicon.ico',
    type: 'site',
  },
]

// 固定组件（如添加按钮）
export const fixedWidgets: WidgetItem[] = [
  { id: 'add-site', size: '1x1', title: '添加网站', icon: Plus, type: 'add-site' },
]
